# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_approver_related', serialize=False, to='app.Employee')),
            ],
            bases=('app.employee',),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_coach_related', serialize=False, to='app.Employee')),
                ('approvers', models.ManyToManyField(related_name='coaches', through='app.ApproverCoach', to='app.Approver')),
            ],
            options={
                'verbose_name_plural': 'coaches',
            },
            bases=('app.employee',),
        ),
        migrations.AddField(
            model_name='feedback360',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
        migrations.AddField(
            model_name='case',
            name='feedback_360_forms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.Feedback360'),
        ),
        migrations.AddField(
            model_name='case',
            name='performance_review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.PerformanceReview'),
        ),
        migrations.AddField(
            model_name='case',
            name='self_evaluation_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.SelfEvaluation'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CaseStatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.Coach'),
        ),
        migrations.AddField(
            model_name='case',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.Coach'),
        ),
        migrations.AddField(
            model_name='approvercoach',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Approver'),
        ),
        migrations.AddField(
            model_name='approvercoach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Coach'),
        ),
    ]
