# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='coach',
        ),
        migrations.AddField(
            model_name='employee',
            name='coach_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Coach'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='employee_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Employee'),
        ),
    ]
