# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160729_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback360',
            name='case',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='case',
        ),
        migrations.RemoveField(
            model_name='selfevaluation',
            name='case',
        ),
    ]
