# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160729_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback360',
            name='submitted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='submitted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='submitted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
