# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160729_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='employee_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Employee'),
        ),
    ]
